### ISSUE TITLE
Upgrade to using cordova-clipboard plugin rather than the universal-clipboard-plugin

### ISSUE THREAD

**Issue by ridan** [vstirbu/InstagramPlugin#104]
The universal-clipboard-plugin barely works and doesn't look like it's maintained anymore. We need to switch to a better clipboard plugin. I would reccomend cordova-clipboard

**Comment by vstirbu** [comment]
Thanks for the suggestion, although I was thinking to remove the dependency on the clipboard plugin altogether. The caption functionality is not part of Instagram application's hooks and can be handled easily outside this plugin by the developer.

**Comment by JustasKuizinas** [comment]
@vstirbu I agree you should remove clipboard dependency because now for example if you have cordova-clipboard installed you get this error while installing cordova-instagram-plugin

Failed to install 'cordova-universal-clipboard': CordovaError: Uh oh!
"D:\...\platforms\android\app\src\main\java\
com\verso\cordova\clipboard\Clipboard.java" already exists!

**Comment by rodrigograca31** [comment]
I know 2 years have passed but I just saw this and seems like a simple fix so I will do it now.

:hugs:
